name = void
title = Void Engine Base
description = Intercepts C++ map generation routines to provide an optimized, void building template with secure node overrides.
developer = jolethen 
version = 1.0.0
depends = default
